### ISSUE TITLE
If statement -> Switch ?

### ISSUE THREAD

**Issue by redahaq** [fac18/week-5-DARK-server-Api#39]
I really love all your logic and how you've created different messages according to night/ day and using the weather code groups. with 'startsWith'. Very clever!

Could you perhaps change your logic of if-else statements to a switch statement with cases and breaks? 

![](https://media.giphy.com/media/VEsfbW0pBu145PPhOi/giphy.gif)

**Comment by plasticneuron** [comment]
Haha thanks Reda this is a nice idea! Always with the excellent memes

![](https://media.giphy.com/media/l3q2wJsC23ikJg9xe/giphy.gif)
